export const LOADING_ME = "LOADING_ME";
export const ERROR_ME = "ERROR_ME";
export const FILL_ME = "FILL_ME";

export const LOADING_AUTHORS = "LOADING_AUTHORS";
export const ERROR_AUTHORS = "ERROR_AUTHORS";
export const FILL_AUTHORS = "FILL_AUTHORS";

export const LOADING_AUTHOR = "LOADING_AUTHOR";
export const ERROR_AUTHOR = "ERROR_AUTHOR";
export const FILL_AUTHOR = "FILL_AUTHOR";

export const LOADING_STORIES = "LOADING_STORIES";
export const ERROR_STORIES = "ERROR_STORIES";
export const FILL_STORIES = "FILL_STORIES";

export const LOADING_MY_STORIES = "LOADING_MY_STORIES";
export const ERROR_MY_STORIES = "ERROR_MY_STORIES";
export const FILL_MY_STORIES = "FILL_MY_STORIES";

export const LOADING_HEARTED_STORIES = "LOADING_HEARTED_STORIES";
export const ERROR_HEARTED_STORIES = "ERROR_HEARTED_STORIES";
export const FILL_HEARTED_STORIES = "FILL_HEARTED_STORIES";
